### ISSUE TITLE
Show INFO logs when not in `-vdebug`

### ISSUE THREAD

**Issue by lyz-code** [soywod/mirador#3]
Hi, I'm setting up `mirador` and I'd like to monitor if the service is up and working as expected. The problem is that if I run `mirador watch` it doesn't send anything to stdout. 

`vdebug` though is too verbose.
 
Would it be possible to send the INFO logs by default?

**Comment by soywod** [comment]
It is a good idea indeed, I could definitely add INFO logs from the CLI, and let the debug ones to the lib.

**Comment by soywod** [comment]
I added 2 basic logs on stdout: when the watch starts and when it get interrupted by CTRL+C.
I also added more INFO logs, so running your watch command with `RUST_LOG=info` should be less verbose than debug logs.

This is not perfect, it should be improved by https://github.com/pimalaya/imap-client/issues/7.

Pre-built binary will be available at https://github.com/pimalaya/mirador/actions/runs/11954898333.
